all:
	g++ -o stream stream.cpp -lsocketpp
	g++ -o server server.cpp -lsocketpp
	g++ -o ping ping.cpp -lsocketpp
	g++ -o htmltree htmltree.cpp -lsocketpp
	g++ -o synflood synflood.cpp -lsocketpp
	g++ -o trace trace.cpp -lsocketpp
clean:
	rm -f *~ server stream ping htmltree synflood trace
