all:
	g++ -o icmp_ip icmp_ip.cpp -lsocketpp
	g++ -o icmp icmp.cpp -lsocketpp
	g++ -o tcp_ip tcp_ip.cpp -lsocketpp
	g++ -o udp_ip udp_ip.cpp -lsocketpp
	g++ -o tcp tcp.cpp -lsocketpp
	g++ -o udp udp.cpp -lsocketpp
clean:
	rm -f *~ tcp udp icmp icmp_ip tcp_ip udp_ip
