all:
	g++ -o icmp_ip icmp_ip.cpp -lsocketpp -g
	g++ -o icmp icmp.cpp -lsocketpp -g
	g++ -o tcp_ip tcp_ip.cpp -lsocketpp -g
	g++ -o udp_ip udp_ip.cpp -lsocketpp -g
	g++ -o tcp tcp.cpp -lsocketpp -g 
	g++ -o udp udp.cpp -lsocketpp -g
clean:
	\rm -f *~ tcp udp icmp icmp_ip tcp_ip udp_ip
